model_name: efficientnet_b0
pretrained: false
num_classes: 1
loss:
  name: aucloss
  args:
    skip: true
    gamma: 0.8
optimizer: 
  name: adamw
  args:
    lr: 1e-1
    weight_decay: 0.
scheduler:
  name: cosine
  args:
    num_warmup_steps: 3
    num_training_steps: 10
trainer:
  max_epochs: 10
  limit_train_batches: 4098
  limit_val_batches: 512
  limit_test_batches: 2048
  num_sanity_val_steps: 128