model_name: efficientnet_b0
pretrained: false
num_classes: 1
loss:
  name: bceloss
  args:
optimizer: 
  name: adamw
  args:
    lr: 6e-3
    weight_decay: 1e-4
scheduler:
  name: cosine
  args:
    num_warmup_steps: 3
    num_training_steps: 10
trainer:
  max_epochs: 10
  limit_train_batches: 2048
  limit_val_batches: 512
  limit_test_batches: 2048
  num_sanity_val_steps: 128