model_name: efficientnet_b0
pretrained: false
num_classes: 2
loss:
  name: celoss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 1e-5
scheduler:
  name: step
  args:
    step_size: 3
    gamma: 0.1
datamodule:
  num_workers: 8
  batch_size: 512
  # shuffle: true
  pin_memory: true
  # prefetch_factor: 2
split: 
  val: .05
  test: .1
trainer:
  max_epochs: 10
  limit_train_batches: 1024
  limit_val_batches: 128
