model_name: efficientnet_b0
pretrained: false
num_classes: 2
loss:
  name: celoss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: cosine
  args:
    num_warmup_steps: 3
    num_training_steps: 14
trainer:
  max_epochs: 10
  limit_train_batches: 1024
  limit_val_batches: 64

  