model_name: efficientnet_b0
pretrained: false
num_classes: 2
loss:
  name: focalloss
  args:
    cls: true
optimizer: 
  name: adamw
  args:
    lr: 5e-3
    weight_decay: 0
scheduler:
  name: cosine
  args:
    num_warmup_steps: 3
    num_training_steps: 16
trainer:
  max_epochs: 8
  limit_train_batches: 2048
  limit_val_batches: 256
  # limit_test_batches: 2048
  num_sanity_val_steps: 128  

  