model_name: efficientnet_b0
pretrained: false
num_classes: 2
loss:
  name: focalloss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: step
  args:
    step_size: 3
    gamma: .1
trainer:
  max_epochs: 8
  limit_train_batches: 2048
  limit_val_batches: 256
  # limit_test_batches: 2048
  num_sanity_val_steps: 128  