model_name: efficientnet_b0
pretrained: false
num_classes: 1
loss:
  name: aucloss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: step
  args:
    step_size: 2
    gamma: .1
trainer:
  max_epochs: 13
  limit_train_batches: 1024
  limit_val_batches: 512
  # limit_test_batches: 2048
  num_sanity_val_steps: 128  