model_name: efficientnet_b0
pretrained: false
num_classes: 1
loss:
  name: bceloss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: linear
  args:
    num_warmup_steps: 3
    num_training_steps: 15
trainer:
  max_epochs: 1
  num_sanity_val_steps: 128  
  limit_train_batches: 1
  limit_val_batches: 1
  limit_test_batches: 1
