type: dml
model_name: efficientnet_b0
pretrained1: true
pretrained2: false
num_intermediate: 100
num_classes: 2
loss:
  name: celoss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 1e-4
scheduler:
  name: step
  args:
    step_size: 2
    gamma: .1
trainer:
  max_epochs: 6
  num_sanity_val_steps: 128  
  limit_val_batches: 512
  limit_test_batches: 2048
