type: dml
model_name: efficientnet_b0
pretrained1: false
pretrained2: true
num_intermediate: 100
num_classes: 2
loss:
  name: celoss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: step
  args:
    step_size: 3
    gamma: .1
trainer:
  max_epochs: 8
  num_sanity_val_steps: 128  
  # gradient_clip_val: 2.