type: paper
num_classes: 1
loss:
  name: bceloss
  args:
optimizer: 
  name: sgd
  args:
    lr: 1e-2
    nesterov: true
    momentum: 0.9
    weight_decay: 1e-2
scheduler:
  name: linear
  args:
    num_warmup_steps: 3
    num_training_steps: 10
trainer:
  max_epochs: 2
  num_sanity_val_steps: 128  
  limit_val_batches: 512
  limit_test_batches: 2048
