type: paper
num_classes: 1
in_channels: 3
loss:
  name: bceloss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: constant
  args:
    num_warmup_steps: 3
trainer:
  max_epochs: 15
  num_sanity_val_steps: 128  
  limit_val_batches: 512
  limit_test_batches: 2048
