type: paper
num_classes: 2
loss:
  name: celoss
  args:
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: step
  args:
    step_size: 3
    gamma: .1
trainer:
  max_epochs: 8
  num_sanity_val_steps: 128  
  limit_val_batches: 512
  limit_test_batches: 2048
