model_name: paper
pretrained: false
num_classes: 1
loss:
  name: aucmarginloss
  args:
    m: 0.9
    p: 0.5
optimizer: 
  name: adamw
  args:
    lr: 1e-2
    weight_decay: 0
scheduler:
  name: linear
  args:
    num_warmup_steps: 3
    num_training_steps: 15
trainer:
  max_epochs: 8
  num_sanity_val_steps: 128  
  limit_val_batches: 512
  limit_test_batches: 2048
