convnet:
  - in_channels: 1
    out_channels: 12
    kernel_size:  3
    stride: 1
    padding: 1

  - in_channels: 12
    out_channels: 32
    kernel_size:  3
    stride: 1
    padding: 1

  - in_channels: 32
    out_channels: 128
    kernel_size:  3
    stride: 1
    padding: 1

  - in_channels: 128
    out_channels: 256
    kernel_size:  3
    stride: 1
    padding: 1

scaling:
  mean: 1
  std: 1e-21