transform: 
  name: cqt                    # melspectrogram, cqt, stft, 
  sr: 2048
  hop_length: 16
  fmin: 20
  n_bins: 256
  bins_per_octave: 60
  norm: true
  basis_norm: 1
  window: hann
  pad_mode: constant
  output_format: Magnitude
  verbose: false

pca: 1
scale: true
