transform: 
  name: cqt                    # melspectrogram, cqt, stft, 
  sr: 2048
  hop_length: 16
  fmin: 20
  n_bins: 256
  bins_per_octave: 60
  norm: true
  basis_norm: 1
  window: hann
  pad_mode: constant
  output_format: Magnitude

scaling:                        # rescale the values to, e.g, [-1, 1]
  - 3
  - 1e-22

augment: false
