transform: 
  name: mel                     # melspectrogram, cqt, dft, 
  # freq_scale: linear            # linear, log, no; relies on the fmin, fmax values
  sr: 2048                      # sampling rate
  n_fft: 128                    # could be a list to denote computing multiple transform for different values of n_fft
  win_length: 128               # should be less than n_fft
  n_mels: 32                    # by default: n_fft//2+1
  hop_length: 32                # stride
  center: true                  # kernel centered around the current sample
  pad_mode: constant            # reflect
  fmin: 20
  fmax: 500
  norm: 1                       # if 1, divide the triangular mel weights by the width of the mel band (area normalization, AKA ‘slaney’ default in librosa). Otherwise, leave all the triangles aiming for a peak value of 1.0
  trainable_STFT: false
  trainable_mel: false    
  verbose: false
scaling:                        # rescale the values to [-1, 1]
  - 0
  - 1e-24

stacking: 0                     # stack signals from the three detectors along this axis
