transform: 
  name: mel                    # melspectrogram, cqt, dft, 
  n_fft: 
    - 64
    - 256
    - 512                       # could be a list to denote computing multiple transform for different values of n_fft
  hop_length: 16                # stride
  center: true                  # kernel centered around the current sample
  pad_mode: constant            # reflect
  fmin: 20
  fmax: 500
  sr: 2048                      # sampling rate
  norm: 1                       # if 1, divide the triangular mel weights by the width of the mel band (area normalization, AKA ‘slaney’ default in librosa). Otherwise, leave all the triangles aiming for a peak value of 1.0
  trainable_STFT: false
  trainable_mel: false    
  verbose: false

scaling:                        # rescale the values to, e.g, [-1, 1]
  - 0
  - 1e-24