transform: 
  name: mel                    # melspectrogram, cqt, stft, 
  sr: 2048
  n_mels: 256
  hop_length: 16
  fmin: 20
  fmax: 500
  window: hann
  center: true
  pad_mode: constant
  htk: true
  verbose: false

scaling:                        # rescale the values to, e.g, [-1, 1]
  - 0.3
  - 1e-41

augment: false
