transform: 
  name: stft                    # melspectrogram, cqt, dft, 
  n_fft: 1024                   # size of fft
  window: hann
  freq_bins: 256                # by default: n_fft//2+1
  hop_length: 16                # stride
  freq_scale: log               # linear, log, no; relies on the fmin, fmax values
  center: true                  # kernel centered around the current sample
  pad_mode: constant            # reflect
  fmin: 20
  fmax: 500
  sr: 2048                      # sampling rate
  output_format: Magnitude          # magnitude, complex, phase; for the last two it returns two channels
  trainable: false    
  verbose: false

pca: 1
scale: true
