transform: 
  name: stft                    # melspectrogram, cqt, dft, 
  n_fft: 
    - 64
    - 128
    - 512                       # could be a list to denote computing multiple transform for different values of n_fft
  hop_length: 16                # stride
  freq_scale: linear            # linear, log, no; relies on the fmin, fmax values
  center: true                  # kernel centered around the current sample
  pad_mode: constant            # reflect
  fmin: 20
  fmax: 500
  sr: 2048                      # sampling rate
  output_format: Magnitude      # magnitude, complex, phase; for the last two it returns two channels
  trainable: false    
  verbose: false
scaling:                        # rescale the values to, e.g, [-1, 1]
  - 0
  - 1e-21

stacking: 0                     # stack signals from the three detectors along this axis: horizontally/vertically